---
jobs:
- name: Manual-trigger
  plan:
  - get: manualtrigger
    trigger: false

- name: purge-mail
  public: true
  serial: true
  plan:
  - get: go-time
    trigger: true
  - get: manualtrigger
    trigger: true
    passed:
      - Manual-trigger
  - task: purge-personal-gmail
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: harbor.high.am/danhigham/purge-gmail
      run:
        path: app
        args:
        - -gmail-creds-path
        - /gmail/creds
        - -gmail-token-path
        - /gmail/token
        - -credhub-url
        - ((credhub_url))
    params:
      CREDHUB_CA_CERT: ((credhub_ca_cert))
      UAA_CA_CERT: ((uaa_ca_cert))
      CREDHUB_CLIENT: ((credhub_client))
      CREDHUB_SECRET: ((credhub_secret))

  - task: purge-work-gmail
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: harbor.high.am/danhigham/purge-gmail
      run:
        path: app
        args:
        - -gmail-creds-path
        - /gmail/creds
        - -gmail-token-path
        - /pivotal-gmail/token
        - -credhub-url
        - ((credhub_url))
    params:
      CREDHUB_CA_CERT: ((credhub_ca_cert))
      UAA_CA_CERT: ((uaa_ca_cert))
      CREDHUB_CLIENT: ((credhub_client))
      CREDHUB_SECRET: ((credhub_secret))

resources:

- name: manualtrigger
  type: time           # technique to trigger and propagate manual execution through pipeline
  source:
    interval: 1m

- name: go-time
  type: time
  source:
    interval: 24h
    location: America/Los_Angeles
