on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '30 9 * * *'

jobs:
  gmail-purge:
    runs-on: ubuntu-latest
    container:
      image: danhigham/gmail-purge:main
    env:
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
    steps:
      - name: run-script
        run: /gmail-purge/purge.py
