on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '30 9 * * *'

  workflow_dispatch:

jobs:
  gmail-purge:
    runs-on: ubuntu-latest
    container:
      image: danhigham/gmail-purge:main
    steps:
      - name: Run purge
        run: ./purge.py
        env:
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}

