on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '30 9 * * *'

jobs:
  gmail-purge:
    runs-on: ubuntu-latest
    steps:
    - name: "Run purge"
      uses: danhigham/gmail-purge:main
      env:
        GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
