on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '30 9 * * *'

jobs:
  gmail-purge:
    container:
      image: danhigham/gmail-purge:main
    env:
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
    steps:
      - name: run-script
        run: ./purge.py
